idf_component_register(SRCS "epet_state.c" "epet_render.c" "epet_event.c" "epet_care.c" "epet_draw.c" "epet_ui.c" "epet_pages.c" "epet_sprite.c" "epet_species.c" "epet_sprites.c" "epet_module.c" "epet_module_core.c" "epet_store.c" "epet_save.c" "epet_dynpage.c" "epet_modblob.c" "epet_link.c" "epet_vm.c"
                       INCLUDE_DIRS ".")
